### ISSUE TITLE
Exchange server different API but functionnal

### ISSUE THREAD

**Issue by darcosion** [Raikia/UhOh365#9]
I've tried this API with a mail and the response was strange : 
```{"Protocol":"Autodiscoverv1","Url":"https://mydomain.extension/api"}```

So I guess the API was changed to redirect to API of exchange server for infrastructures with Exchange server.

It's specific but we should add an exception for that.

Regards

**Comment by Raikia** [comment]
If you give an example email set, I can test what you mean.  If you'd like to privately share, send to raikiasec@gmail.com.  Its hard to debug something like this generically because o365 has some absurd and irregular API responses

**Comment by Raikia** [comment]
Whoops didnt mean to close

**Comment by Raikia** [comment]
Spoke with @darcosion via email and the issue was that the domain wasn't configured for o365 and @darcosion misunderstood how this technique works.  For someone who might find this in the future:

This is actually (unfortunately) part of how Exchange works.  That “It doesn’t look like XYZ uses o365” print that UhOh365 displays is because of that redirect.  If you look at how the requests work, here is a domain that does use o365:

 ![Image1](https://i.imgur.com/Kz5pbFh.jpg)

If a domain doesn’t use o365, it redirects to the domain **whether or not it exists at all**.  It doesn’t mean that it knows the API exists, it just redirects to it anyway.  Like this:

![Image2](https://i.imgur.com/fAOQOkt.jpg)

So following the redirect there won’t be helpful because the majority of the time, that redirect will probably not actually exist.

The results UhOh365 reveal some different information:
   * If the domain uses o365 (so it is like the first screenshot above), we can know if an email is valid or not
   * If the domain does not use o365 (like the second screenshot), we can see if the email has a msft account (and thus is valid), but we cannot determine if the email doesn’t exist
